CREATE TABLE [dbo].[Turma]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	[Ativo] BIT NOT NULL,
    [Nome] VARCHAR(100) NOT NULL, 
    [Materia] VARCHAR(50) NOT NULL, 
    [DatInc] DATETIME NOT NULL DEFAULT GETDATE(), 
    [DatAlt] DATETIME NOT NULL DEFAULT GETDATE()
)
